### ISSUE TITLE
オリジナルサイズの画像を利用したい

### ISSUE THREAD

**Issue by matoken** [slimymars/mikutter-google-photos-uploader#3]
Twitterオリジナルサイズの画像をGoogle Photoにアップロードできると嬉しいです．
https://twitter.com/matoken/status/836782402118656002

画像URLの末尾に :orig をつけるといけそうです．
- [Twitter の画像 URL に :orig をつけると元画像が取得できる（できない場合もある） - ヤルキデナイズド](http://uasi.hatenablog.com/entry/2014/08/27/100933 "Twitter の画像 URL に :orig をつけると元画像が取得できる（できない場合もある） - ヤルキデナイズド")

こんな感じかなと思ったのですがうまく行ったり落ちたりします．
＃ruby素人ですorz

```
$ git diff
diff --git a/mikutter-google-photos-uploader.rb b/mikutter-google-photos-uploader.rb
index 36c9be3..3642379 100644
--- a/mikutter-google-photos-uploader.rb
+++ b/mikutter-google-photos-uploader.rb
@@ -120,6 +120,8 @@ SUMMARY
     threads = []
     message.entity.select { |e| e[:type] == 'photo' }.map do |e|
       threads << Thread.new do
+        e[:url].slice!(/:large$|:thumb$|:orig$/)
+        e[:url] << ':orig'
         open(e[:url]) { |f|
           res = gp.upload_image(f, f.content_type, album_id:album_id, title: e[:url], summary: summary)
           if res.code != '201'
```

**Comment by slimymars** [comment]
気付くの遅れた……
今更ですが、コード参考にしてbranch作って入れました。
大丈夫そうならmasterにマージします。

**Comment by slimymars** [comment]
マージしたのでクローズします。
